<?php
return array(
	array(
		'alias'=>'index',
		'description'=>'首页',
	),
	array(
		'alias'=>'index-contact-area',
		'description'=>'首页联系我们',
	),
	array(
		'alias'=>'post-list-sidebar',
		'description'=>'商品列表页侧边栏',
	),
	array(
		'alias'=>'index-banner',
		'description'=>'首页顶部Banner',
	),
	array(
		'alias'=>'index-contact-baidu-map',
		'description'=>'首页百度地图外层元素',
	),
);